name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make ninja-build gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Create build dir
        run: mkdir -p build

      - name: Configure
        working-directory: build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi.cmake

      - name: Build
        working-directory: build
        run: cmake --build . --config Release